### ISSUE TITLE
Implement statistics support

### ISSUE THREAD

**Issue by niemyjski** [niemyjski/homeassistant-kohler#12]
https://developers.home-assistant.io/blog/2021/09/20/state_class_total
https://developers.home-assistant.io/blog/2021/08/16/state_class_total
https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes

**Comment by dcmeglio** [comment]
What was the intent for these?

**Comment by niemyjski** [comment]
@dcmeglio I was thinking that we may need to implement new sensor attributes like https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/#state_class to enable statistics but I wasn't sure. I'd like to have long term history that is very cheap on storage side. I'm really not sure though, just added this here for investigation.
