### ISSUE TITLE
Shower lights support

### ISSUE THREAD

**Issue by bytenik** [niemyjski/homeassistant-kohler#22]
Do you have a DTV+ shower light? I do not, they were already discontinued by the time I bought my DTV+ system. If you do, I'd like to work with you to reverse engineer it if possible so I could have my DTV+ keypad control a different lighting system. Are you open to that?

**Comment by niemyjski** [comment]
I do not have the shower lights, but the python library has the api for turning on the light. I'm just not sure if it works.
