### ISSUE TITLE
Required parts?

### ISSUE THREAD

**Issue by dgrnbrg** [niemyjski/homeassistant-kohler#23]
Hi! I'm trying to get this set up, and I was wondering which parts you have in your shower/which are necessary?

It seems clear that I'd need [this system controller](https://www.us.kohler.com/webassets/kpna/catalog/pdf/en/K-99695_spec.pdf).

That device says that it [requires this interface](https://www.us.kohler.com/webassets/kpna/catalog/pdf/en/K-99693_spec.pdf), so I was wondering if you have an interface too and think it's necessary?

Lastly, my distributor is insisting that I also need [this wifi module](https://www.us.kohler.com/webassets/kpna/catalog/pdf/en/K-97999_spec_US-CA_Kohler_en.pdf) for Kohler Konnect, but it doesn't seem necessary. Did you need the wifi konnect module?

**Comment by 38Cherry** [comment]
you need the system controller and the touch panel for sure.  You do NOT need the Kohler Konnect unless you want to use voice control (alexa or google home) or your phone to control the shower.  I do have it and do have an Alexa in my bathroom that my wife uses every day to turn on the preheat for the shower and to set it to her temp.  All this CAN be done with home assistant and/or the touch panel.  If you are going to drop 4k on a shower system you might as well spend the extra $500 and get a konnect.  The Konnect does NOT interface with home assistant.
