### ISSUE TITLE
Add Switches for all the valves

### ISSUE THREAD

**Issue by smarthomeaf** [niemyjski/homeassistant-kohler#25]
Does the local API have the ability control the individual Outlets on the valves?  Currently the outlets are only showing up as sensors.   It would be nice to setup automations to turn on the individual outlets depending where a person is in shower.   (mwave sensors)

<img width="1268" alt="image" src="https://github.com/niemyjski/homeassistant-kohler/assets/105226208/b3422616-a737-4637-b549-bc7a5b289f09">

**Comment by niemyjski** [comment]
I'm not sure, I don't have any of these. If you can control them in the ui, you can control them via the api, might just need some library updates

**Comment by smarthomeaf** [comment]
Let me know what I can do to help, or what you need.   If I provide a .har file from me turning the Outlets on and off help?


<img width="461" alt="image" src="https://github.com/niemyjski/homeassistant-kohler/assets/105226208/7a379329-0e0c-4abd-9a71-35155c925aa4">

**Comment by niemyjski** [comment]
I'd start by cloning the Kohler python library and try to activate these valves via the library.

**Comment by niemyjski** [comment]
This has been added in 0.4.0
