### ISSUE TITLE
Outlet sensors now working

### ISSUE THREAD

**Issue by smarthomeaf** [niemyjski/homeassistant-kohler#26]
Outlet sensors not reflecting when they are on or off.    Only the main valve is showing on or off.

<img width="821" alt="image" src="https://github.com/niemyjski/homeassistant-kohler/assets/105226208/4a5de80c-1b70-4239-a81c-0ccfa9d2a74a">

**Comment by niemyjski** [comment]
I don't have any of these so will need help on this one. I'd start with the python library

**Comment by niemyjski** [comment]
I think this has been resolved in the latest release.
