### ISSUE TITLE
Shower turns off by it self during warm up purge 

### ISSUE THREAD

**Issue by 38Cherry** [niemyjski/homeassistant-kohler#29]
Does anyone else have an issue where the shower will turn off all by itself?  It always happens during the warm up/purge period. I don't think it's a HA integration thing but just asking other people who have it and use the automations to turn on the shower vs the keypad.

**Comment by niemyjski** [comment]
I have only seen this once, and I thought it was due to water hitting the display a few months back. I'd look at the logs in the shower control panel (via browser) when this happens.

**Comment by niemyjski** [comment]
I'm going to close this, but if anyone sees this behavior please comment with any logs and we will reopen and look into it further.
