### ISSUE TITLE
Valve naming is not correct

### ISSUE THREAD

**Issue by jwelter1971** [niemyjski/homeassistant-kohler#5]
I have one valve in my system, and it is the 6 port version.

It is detected and represented as:

binary_sensor.kohler_valve_1
binary_sensor.kohler_valve_1_outlet_1
....
binary_sensor.kohler_valve_1_outlet_5

I believe the first entity should be outlet_1 and the last outlet_6 as it would be consistent to the Kohler WebUI

**Comment by niemyjski** [comment]
I’m in the same setup, I followed a pattern that would be more explicit and support endless outlets. Do you have all 6 ports installed? Can you share what your ui looks like

**Comment by jwelter1971** [comment]
![Screen Shot 2020-02-03 at 11 14 02 AM](https://user-images.githubusercontent.com/9425959/73671750-956a9a00-4679-11ea-8cb3-096a675826db.png)
![Screen Shot 2020-02-03 at 11 13 35 AM](https://user-images.githubusercontent.com/9425959/73671751-956a9a00-4679-11ea-8978-9f07cfabc886.png)

**Comment by jwelter1971** [comment]
Hi, I came from the original DTV system when only the 6 port was available.  Have updated it with the DTV+ upgrade kit (controller, cable, and interface screen).

So my system is setup with outlet 1 being a rain shower (and default), outlet 2 is a hand shower, and outlet 3,4,5,6 are body jets part of the massage group (or as kids call it the car wash).

See the screen shots.  Also sent firmware version screen.  Seems an update came out in the past few weeks that added the Kohler Konnect gateway option.

**Comment by niemyjski** [comment]
So your saying you have 6 outlets configured but only seeing 5

**Comment by jwelter1971** [comment]
No,

I am just saying they are named incorrectly.

They are named as:

binary_sensor.kohler_valve_1
binary_sensor.kohler_valve_1_outlet_1
....
binary_sensor.kohler_valve_1_outlet_5

and should be:

binary_sensor.kohler_valve_1_outlet_1
...
binary_sensor.kohler_valve_1_outlet_6

**Comment by niemyjski** [comment]
I have sensors for the valve and valve outlets so you can see if water is running and to what valve

**Comment by niemyjski** [comment]
Can you email me the json payloads of the sysinfo and values.cgi calls your browsers making. Check my profile for the address.

**Comment by jwelter1971** [comment]
Please see attached for the sysinfo response:

`{"valve1_Currentstatus":"Off","degree_symbol":"&degC","valve1Setpoint":"38.0","valve1outlet1":true,"valve1outlet2":false,"valve1outlet3":false,"valve1outlet4":false,"valve1outlet5":false,"valve1outlet6":false,"valve1_massage":0,"valve2_Currentstatus":"","valve2Setpoint":"38.0","valve2outlet1":false,"valve2outlet2":false,"valve2outlet3":false,"valve2outlet4":false,"valve2outlet5":false,"valve2outlet6":false,"valve2_massage":0,"steamStatus":"","steamTempStatus":"43.5","steamTimeStatus":"-9:00","steamTimeMinutes":"-9","LZ1Status":"Off","LZ2Status":"Off","LZ3Status":"Off","RainpanelStatus":"Off","light_attach":"0","light_remove":"0","light_turnoff1":"0","light_turnoff2":"0","light_turnoff3":"0","spa_on":false,"ui_shower_on":false,"ui_steam_running":false,"devices_running":false}`

**Comment by jwelter1971** [comment]
And the values response:

`{"white":1,"effect":1,"fade":1,"rain_brightness":100,"v1_threeport_flow":false,"one_type":"outlet_5","two_type":"outlet_2","three_type":"outlet_11","four_type":"outlet_11","five_type":"outlet_11","six_type":"outlet_11","purge_0":true,"purge_1":false,"purge_2":false,"purge_3":false,"purge_4":false,"purge_5":false,"num_outlets":6,"def_outlet":1,"def_control_outlet":1,"def_deluge_valve":1,"def_deluge_outlet":1,"one_massage":false,"two_massage":false,"three_massage":true,"four_massage":true,"five_massage":true,"six_massage":true,"valve1_massage":0,"outlet_0_flow":0,"outlet_0_ramp":1,"outlet_1_flow":0,"outlet_1_ramp":1,"outlet_2_flow":0,"outlet_2_ramp":1,"v1_cal_code":169,"cold_water":1,"max_valve1_runtime_enable":1,"max_valve1_runtime":1,"max_valve2_runtime_enable":0,"max_valve2_runtime":0,"max_steam_runtime_enable":0,"max_steam_runtime":0,"auto_purge_enable":0,"auto_purge":0,"def_temp":"38.0","max_temp":"45.0","v1c1":"","v1c2":"","valve1PortsAvailable":"6","valve2PortsAvailable":"0","ShowerConfiguration":127,"custom_v1c1":0,"custom_v1c2":0,"custom_v2c1":1,"custom_v2c2":1,"valve1_ErrorFatal":0,"valve1_ErrorResettable":0,"v2_threeport_flow":false,"v2_one_type":"outlet_0","v2_two_type":"outlet_0","v2_three_type":"outlet_0","v2_four_type":"outlet_0","v2_five_type":"outlet_0","v2_six_type":"outlet_0","purgev2_0":false,"purgev2_1":false,"purgev2_2":false,"purgev2_3":false,"purgev2_4":false,"purgev2_5":false,"v2_num_outlets":0,"v2_def_outlet":0,"v2_one_massage":false,"v2_two_massage":false,"v2_three_massage":false,"v2_four_massage":false,"v2_five_massage":false,"v2_six_massage":false,"valve2_massage":0,"v2_outlet_0_flow":0,"v2_outlet_0_ramp":1,"v2_outlet_1_flow":0,"v2_outlet_1_ramp":1,"v2_outlet_2_flow":0,"v2_outlet_2_ramp":1,"v2_cal_code":0,"v2_cold_water":1,"v2_auto_purge":0,"v2_def_temp":"38.0","v2_max_temp":"45.0","v2c1":"","v2c2":"","valve2_ErrorFatal":0,"valve2_ErrorResettable":0,"saved_defaults":true,"gen1connected":true,"gen2connected":false,"time_check_format":0,"date_check_format":2,"dry_contact":false,"config":0,"units":1,"ui_settings_locked":false,"ui_user_locked":false,"web_locked":false,"relay1_string":"Relay 1","relay2_string":"Relay 2","contact1_string":"Contact 1","contact2_string":"Contact 2","daylight":false,"steam_select":false,"massage":true,"spa":false,"spa_breathe":false,"spa_release":false,"spa_exhilerate":false,"spa_warmup":false,"spa_cooldown":false,"spa_renew":false,"spa_headaid":false,"spa_flex":false,"spa_detox":false,"spa_steamcoach":false,"spa_repair":false,"spa_breathe_config":false,"spa_release_config":false,"spa_exhilerate_config":false,"spa_warmup_config":false,"spa_cooldown_config":false,"spa_renew_config":false,"spa_headaid_config":false,"spa_flex_config":false,"spa_detox_config":false,"spa_steamcoach_config":false,"spa_repair_config":false,"langIndex":0,"relay_1_on_trigger":0,"relay_1_off_trigger":0,"relay_1_on_delay":0,"relay_1_off_delay":0,"relay_2_on_trigger":0,"relay_2_off_trigger":0,"relay_2_on_delay":0,"relay_2_off_delay":0,"contact_1_on_trigger":0,"contact_1_off_trigger":0,"contact_1_on_delay":10,"contact_1_off_delay":10,"contact_2_on_trigger":0,"contact_2_off_trigger":0,"contact_2_on_delay":10,"contact_2_off_delay":10,"light3_installed":false,"light2_installed":false,"light1_installed":false,"bridge_installed":false,"rain_installed":false,"light1_level":100,"light2_level":100,"light3_level":100,"light1_delay":0,"light2_delay":0,"light3_delay":0,"light1_fade":30,"light2_fade":30,"light3_fade":30,"light1_type":0,"light2_type":0,"light3_type":0,"light1_name":"Light 1","light2_name":"Light 2","light3_name":"Light 3","rain_fade":1,"rain_brightness":100,"rain_white":1,"rain_speed":1,"massage_enabled":true,"music_installed":false,"valve1_installed":true,"valve2_installed":false,"amp_installed":false,"steam_installed":false,"light3_installed":false,"light2_installed":false,"light1_installed":false,"rainpanel_installed":false,"rainpanel2_installed":false,"konnect_installed":false,"konnectversion_string":"not_seen","coprockonnectversion_string":"not_seen","konnectmac_string":"0.0.0.0.0.0","konnectip_string":"0.0.0.0","konnectSSID":"not_seen","konnectmode":"not_seen","wifistatus_string":"OFF","wifistrength_string":" 0 dBm","valve2_outlet_num":0,"valve1_outlet_num":6,"user1_string":"John","user2_string":"Kim","user3_string":"Preset 3","user4_string":"Preset 4","user5_string":"Preset 5","user6_string":"Preset 6","shower_on":false,"steam_running":false,"control_page_shower":1,"control_page_steam":0,"control_page_user":0,"valve1_temp_string":38.0,"valve2_temp_string":38.0,"steam_max_temp_string":52.0,"steam_def_time_string":10,"steam_power_clean_string":20.0,"valve1_def_outlet":1,"valve2_def_outlet":0,"steam_temp_string":43.5,"steam_time_string":10,"steamTimeRemaining":"-9","amp_volume_string":50,"valve1_outlet1_func":{"func":5,"id":1},"valve1_outlet2_func":{"func":2,"id":2},"valve1_outlet3_func":{"func":11,"id":3},"valve1_outlet4_func":{"func":11,"id":4},"valve1_outlet5_func":{"func":11,"id":5},"valve1_outlet6_func":{"func":11,"id":6},"num_interface":1,"interface1_beep_input":95,"interface1_auto_dim_input":true,"interface1_auto_return_input":true,"interface1_start_screen_input":2,"interface1_curr_name_input":"un-named UI","interface2_beep_input":0,"interface2_auto_dim_input":false,"interface2_auto_return_input":false,"interface2_start_screen_input":0,"interface2_curr_name_input":"","interface3_beep_input":0,"interface3_auto_dim_input":false,"interface3_auto_return_input":false,"interface3_start_screen_input":0,"interface3_curr_name_input":"","user_1":"John","user_2":"Kim","user_3":"Preset 3","user_4":"Preset 4","user_5":"Preset 5","user_6":"Preset 6","user_1_enabled":"false","user_2_enabled":"true","user_3_enabled":"false","user_4_enabled":"false","user_5_enabled":"false","user_6_enabled":"false","CurrentUser":"0","ui1_con_string":"conn","ui2_con_string":"not_seen","ui3_con_string":"not_seen","valve_1_con_string":"conn","valve_2_con_string":"not_seen","controller_con_string":"conn","music_module_con_string":"not_seen","lighting_con_string":"not_seen","steam_con_string":"not_seen","amp_con_string":"not_seen","watertile_con_string":"not_seen","watertile2_con_string":"not_seen","steam_default_string_temp":43.5,"steam_max_temp_string":52.0,"steam_def_time_string":10,"steam_power_clean_string":580.0,"pin_string":"0000","key_string":"Kohler KA02","device_string":"","volume":50,"treble":100,"bass":100,"balance":100,"amulet_version_string":"0.1.3.72","language_version_string":"255.255.255.255","coproc_version_string":"0.0.3.0","touch_version_string":"0.0.0.9","UI1_Type":"0","amulet2_version_string":"not_seen","language2_version_string":"not_seen","coproc2_version_string":"not_seen","touch2_version_string":"not_seen","amulet3_version_string":"not_seen","language3_version_string":"not_seen","coproc3_version_string":"not_seen","touch3_version_string":"not_seen","valve_1_version_string":"0.12","valve_2_version_string":"not_seen","controller_version_string":"0.0.3.78","music_module_version_string":"not_seen","lighting_version_string":"not_seen","steam_version_string":"not_seen","amp_version_string":"not_seen","watertile_version_string":"not_seen","watertile_2_version_string":"not_seen","time":"2020/2/4 09:50 A -0500","date_format":"yy/mm/dd","time_format":"hh:mm T z","IP":"192.168.10.74","gateway":"192.168.10.1","MAC":"00:14:6F:0E:45:EB","SSID":"","const_hospitality":"00","upload_enable":"true","shower_steam_running":"false","hide_all":"true"}`

**Comment by niemyjski** [comment]
Thanks! I'll get this fixed

**Comment by niemyjski** [comment]
Thanks for reporting this and sending me the data. It looks like I had a logic bug with ranges.
