### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by dcmeglio** [niemyjski/homeassistant-kohler#8]
Is this still maintained?

**Comment by niemyjski** [comment]
Yes, I'm using it and making small updates to support latest versions. I am willing to accept prs / any help.

**Comment by dcmeglio** [comment]
Cool. I'll definitely be contributing at some point. I'm new to Home Assistant from Hubitat. I built a DTV+ integration for Hubitat that has a bit more features (individual vale control, light/music control via the Konnect module -- because none of the DTV+ controller commands seemed to work!). I'm new to HA and to Python but as I learn I'll try to contribute, if you're interested in stealing any of my code it's all here https://github.com/dcmeglio/hubitat-kohlerdtv

**Comment by niemyjski** [comment]
Awesome! Yeah I think the biggest help could be getting this to work with config flow, statistics and device support that was added to ha over past year. Would be good to have variable rate polling based on interaction/running. I also wrote the python library and would be willing to help test / merge or answer any questions.

I may have also figured out how to get verdera mirrors to work.

**Comment by dcmeglio** [comment]
Cool. I'll definitely take a look. Still getting situated with Home Assistant but I plan to jump into some coding once I get up and running. The DTV+ is the only Kohler device I have so it's what I focus on. I looked at the Verdera but my bathroom has two mirrors so I'd need to buy two so they match. And it seemed stupid to buy a $1500 mirror and have to turn off the smart features because I don't need 2 alexas within 10ft of each other! 

But I do plan to take a look at the DTV+ code here and see if I can help. The DTV is probably my favorite (and most expensive!) smart device.

**Comment by niemyjski** [comment]
@dcmeglio I created some issues here with things I mentioned above. Also please feel free to join my smart home discord: https://discord.gg/cYAYt8Ps

**Comment by niemyjski** [comment]
@dcmeglio I think this one is of the highest importance. If you have any time and could look at this one that would be awesome: https://github.com/niemyjski/homeassistant-kohler/issues/15
