### ISSUE TITLE
Add config flow support

### ISSUE THREAD

**Issue by niemyjski** [niemyjski/homeassistant-kohler#9]

**Comment by dcmeglio** [comment]
If you're interested, I still have more to do, but got a very basic config flow implementation working https://github.com/dcmeglio/homeassistant-kohler/tree/configflow

**Comment by niemyjski** [comment]
Yes, that would be amazing!

Looking at your branch, I guess I missed the domain being deprecated on configuration settings. Also, where did you get your model number? I don't see it anywhere listed on the Kohler network settings pages

**Comment by dcmeglio** [comment]
I didn't see any way to pull it from the api, right now I just hard coded it because I think that's the only controller Kohler makes? Yeah I get this isn't a good solution :)

**Comment by dcmeglio** [comment]
Also I got some logos merged into the HA brands repo so it looks a little nicer now 
![image](https://user-images.githubusercontent.com/21957250/192398907-f2a66459-bc3f-49ac-9f6a-c837af48482d.png)
